// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestData.proto

package com.eaglesakura.android.service.dummy;

public final class TestData {
  private TestData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SimpleMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eaglesakura_ace_internal.SimpleMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 intValue = 1;</code>
     */
    boolean hasIntValue();
    /**
     * <code>optional int32 intValue = 1;</code>
     */
    int getIntValue();

    /**
     * <code>optional int64 longValue = 2;</code>
     */
    boolean hasLongValue();
    /**
     * <code>optional int64 longValue = 2;</code>
     */
    long getLongValue();

    /**
     * <code>optional string stringValue = 3;</code>
     */
    boolean hasStringValue();
    /**
     * <code>optional string stringValue = 3;</code>
     */
    java.lang.String getStringValue();
    /**
     * <code>optional string stringValue = 3;</code>
     */
    com.google.protobuf.ByteString
        getStringValueBytes();

    /**
     * <code>optional float floatValue = 4;</code>
     */
    boolean hasFloatValue();
    /**
     * <code>optional float floatValue = 4;</code>
     */
    float getFloatValue();

    /**
     * <code>optional double doubleValue = 5;</code>
     */
    boolean hasDoubleValue();
    /**
     * <code>optional double doubleValue = 5;</code>
     */
    double getDoubleValue();

    /**
     * <code>optional bool boolValue = 6;</code>
     */
    boolean hasBoolValue();
    /**
     * <code>optional bool boolValue = 6;</code>
     */
    boolean getBoolValue();
  }
  /**
   * Protobuf type {@code eaglesakura_ace_internal.SimpleMessage}
   */
  public static final class SimpleMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:eaglesakura_ace_internal.SimpleMessage)
      SimpleMessageOrBuilder {
    // Use SimpleMessage.newBuilder() to construct.
    private SimpleMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SimpleMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SimpleMessage defaultInstance;
    public static SimpleMessage getDefaultInstance() {
      return defaultInstance;
    }

    public SimpleMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SimpleMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              intValue_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              longValue_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              stringValue_ = bs;
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              floatValue_ = input.readFloat();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              doubleValue_ = input.readDouble();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              boolValue_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eaglesakura.android.service.dummy.TestData.internal_static_eaglesakura_ace_internal_SimpleMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eaglesakura.android.service.dummy.TestData.internal_static_eaglesakura_ace_internal_SimpleMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eaglesakura.android.service.dummy.TestData.SimpleMessage.class, com.eaglesakura.android.service.dummy.TestData.SimpleMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<SimpleMessage> PARSER =
        new com.google.protobuf.AbstractParser<SimpleMessage>() {
      public SimpleMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimpleMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SimpleMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int INTVALUE_FIELD_NUMBER = 1;
    private int intValue_;
    /**
     * <code>optional int32 intValue = 1;</code>
     */
    public boolean hasIntValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 intValue = 1;</code>
     */
    public int getIntValue() {
      return intValue_;
    }

    public static final int LONGVALUE_FIELD_NUMBER = 2;
    private long longValue_;
    /**
     * <code>optional int64 longValue = 2;</code>
     */
    public boolean hasLongValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 longValue = 2;</code>
     */
    public long getLongValue() {
      return longValue_;
    }

    public static final int STRINGVALUE_FIELD_NUMBER = 3;
    private java.lang.Object stringValue_;
    /**
     * <code>optional string stringValue = 3;</code>
     */
    public boolean hasStringValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string stringValue = 3;</code>
     */
    public java.lang.String getStringValue() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stringValue_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stringValue = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLOATVALUE_FIELD_NUMBER = 4;
    private float floatValue_;
    /**
     * <code>optional float floatValue = 4;</code>
     */
    public boolean hasFloatValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional float floatValue = 4;</code>
     */
    public float getFloatValue() {
      return floatValue_;
    }

    public static final int DOUBLEVALUE_FIELD_NUMBER = 5;
    private double doubleValue_;
    /**
     * <code>optional double doubleValue = 5;</code>
     */
    public boolean hasDoubleValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional double doubleValue = 5;</code>
     */
    public double getDoubleValue() {
      return doubleValue_;
    }

    public static final int BOOLVALUE_FIELD_NUMBER = 6;
    private boolean boolValue_;
    /**
     * <code>optional bool boolValue = 6;</code>
     */
    public boolean hasBoolValue() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool boolValue = 6;</code>
     */
    public boolean getBoolValue() {
      return boolValue_;
    }

    private void initFields() {
      intValue_ = 0;
      longValue_ = 0L;
      stringValue_ = "";
      floatValue_ = 0F;
      doubleValue_ = 0D;
      boolValue_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, intValue_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, longValue_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getStringValueBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, floatValue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, doubleValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, boolValue_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, intValue_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, longValue_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getStringValueBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, floatValue_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, doubleValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, boolValue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.eaglesakura.android.service.dummy.TestData.SimpleMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eaglesakura.android.service.dummy.TestData.SimpleMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eaglesakura.android.service.dummy.TestData.SimpleMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eaglesakura.android.service.dummy.TestData.SimpleMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eaglesakura.android.service.dummy.TestData.SimpleMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.eaglesakura.android.service.dummy.TestData.SimpleMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.eaglesakura.android.service.dummy.TestData.SimpleMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.eaglesakura.android.service.dummy.TestData.SimpleMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.eaglesakura.android.service.dummy.TestData.SimpleMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.eaglesakura.android.service.dummy.TestData.SimpleMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.eaglesakura.android.service.dummy.TestData.SimpleMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eaglesakura_ace_internal.SimpleMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eaglesakura_ace_internal.SimpleMessage)
        com.eaglesakura.android.service.dummy.TestData.SimpleMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eaglesakura.android.service.dummy.TestData.internal_static_eaglesakura_ace_internal_SimpleMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eaglesakura.android.service.dummy.TestData.internal_static_eaglesakura_ace_internal_SimpleMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eaglesakura.android.service.dummy.TestData.SimpleMessage.class, com.eaglesakura.android.service.dummy.TestData.SimpleMessage.Builder.class);
      }

      // Construct using com.eaglesakura.android.service.dummy.TestData.SimpleMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        intValue_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        longValue_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        stringValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        floatValue_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        doubleValue_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        boolValue_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eaglesakura.android.service.dummy.TestData.internal_static_eaglesakura_ace_internal_SimpleMessage_descriptor;
      }

      public com.eaglesakura.android.service.dummy.TestData.SimpleMessage getDefaultInstanceForType() {
        return com.eaglesakura.android.service.dummy.TestData.SimpleMessage.getDefaultInstance();
      }

      public com.eaglesakura.android.service.dummy.TestData.SimpleMessage build() {
        com.eaglesakura.android.service.dummy.TestData.SimpleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.eaglesakura.android.service.dummy.TestData.SimpleMessage buildPartial() {
        com.eaglesakura.android.service.dummy.TestData.SimpleMessage result = new com.eaglesakura.android.service.dummy.TestData.SimpleMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.intValue_ = intValue_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.longValue_ = longValue_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.stringValue_ = stringValue_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.floatValue_ = floatValue_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.doubleValue_ = doubleValue_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.boolValue_ = boolValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eaglesakura.android.service.dummy.TestData.SimpleMessage) {
          return mergeFrom((com.eaglesakura.android.service.dummy.TestData.SimpleMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.eaglesakura.android.service.dummy.TestData.SimpleMessage other) {
        if (other == com.eaglesakura.android.service.dummy.TestData.SimpleMessage.getDefaultInstance()) return this;
        if (other.hasIntValue()) {
          setIntValue(other.getIntValue());
        }
        if (other.hasLongValue()) {
          setLongValue(other.getLongValue());
        }
        if (other.hasStringValue()) {
          bitField0_ |= 0x00000004;
          stringValue_ = other.stringValue_;
          onChanged();
        }
        if (other.hasFloatValue()) {
          setFloatValue(other.getFloatValue());
        }
        if (other.hasDoubleValue()) {
          setDoubleValue(other.getDoubleValue());
        }
        if (other.hasBoolValue()) {
          setBoolValue(other.getBoolValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.eaglesakura.android.service.dummy.TestData.SimpleMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.eaglesakura.android.service.dummy.TestData.SimpleMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int intValue_ ;
      /**
       * <code>optional int32 intValue = 1;</code>
       */
      public boolean hasIntValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 intValue = 1;</code>
       */
      public int getIntValue() {
        return intValue_;
      }
      /**
       * <code>optional int32 intValue = 1;</code>
       */
      public Builder setIntValue(int value) {
        bitField0_ |= 0x00000001;
        intValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 intValue = 1;</code>
       */
      public Builder clearIntValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        intValue_ = 0;
        onChanged();
        return this;
      }

      private long longValue_ ;
      /**
       * <code>optional int64 longValue = 2;</code>
       */
      public boolean hasLongValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 longValue = 2;</code>
       */
      public long getLongValue() {
        return longValue_;
      }
      /**
       * <code>optional int64 longValue = 2;</code>
       */
      public Builder setLongValue(long value) {
        bitField0_ |= 0x00000002;
        longValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 longValue = 2;</code>
       */
      public Builder clearLongValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        longValue_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object stringValue_ = "";
      /**
       * <code>optional string stringValue = 3;</code>
       */
      public boolean hasStringValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string stringValue = 3;</code>
       */
      public java.lang.String getStringValue() {
        java.lang.Object ref = stringValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stringValue_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stringValue = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        java.lang.Object ref = stringValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stringValue = 3;</code>
       */
      public Builder setStringValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        stringValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stringValue = 3;</code>
       */
      public Builder clearStringValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        stringValue_ = getDefaultInstance().getStringValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string stringValue = 3;</code>
       */
      public Builder setStringValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        stringValue_ = value;
        onChanged();
        return this;
      }

      private float floatValue_ ;
      /**
       * <code>optional float floatValue = 4;</code>
       */
      public boolean hasFloatValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float floatValue = 4;</code>
       */
      public float getFloatValue() {
        return floatValue_;
      }
      /**
       * <code>optional float floatValue = 4;</code>
       */
      public Builder setFloatValue(float value) {
        bitField0_ |= 0x00000008;
        floatValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float floatValue = 4;</code>
       */
      public Builder clearFloatValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        floatValue_ = 0F;
        onChanged();
        return this;
      }

      private double doubleValue_ ;
      /**
       * <code>optional double doubleValue = 5;</code>
       */
      public boolean hasDoubleValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double doubleValue = 5;</code>
       */
      public double getDoubleValue() {
        return doubleValue_;
      }
      /**
       * <code>optional double doubleValue = 5;</code>
       */
      public Builder setDoubleValue(double value) {
        bitField0_ |= 0x00000010;
        doubleValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double doubleValue = 5;</code>
       */
      public Builder clearDoubleValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        doubleValue_ = 0D;
        onChanged();
        return this;
      }

      private boolean boolValue_ ;
      /**
       * <code>optional bool boolValue = 6;</code>
       */
      public boolean hasBoolValue() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bool boolValue = 6;</code>
       */
      public boolean getBoolValue() {
        return boolValue_;
      }
      /**
       * <code>optional bool boolValue = 6;</code>
       */
      public Builder setBoolValue(boolean value) {
        bitField0_ |= 0x00000020;
        boolValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool boolValue = 6;</code>
       */
      public Builder clearBoolValue() {
        bitField0_ = (bitField0_ & ~0x00000020);
        boolValue_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:eaglesakura_ace_internal.SimpleMessage)
    }

    static {
      defaultInstance = new SimpleMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:eaglesakura_ace_internal.SimpleMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eaglesakura_ace_internal_SimpleMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eaglesakura_ace_internal_SimpleMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016TestData.proto\022\030eaglesakura_ace_intern" +
      "al\"\205\001\n\rSimpleMessage\022\020\n\010intValue\030\001 \001(\005\022\021" +
      "\n\tlongValue\030\002 \001(\003\022\023\n\013stringValue\030\003 \001(\t\022\022" +
      "\n\nfloatValue\030\004 \001(\002\022\023\n\013doubleValue\030\005 \001(\001\022" +
      "\021\n\tboolValue\030\006 \001(\010B\'\n%com.eaglesakura.an" +
      "droid.service.dummy"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_eaglesakura_ace_internal_SimpleMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eaglesakura_ace_internal_SimpleMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eaglesakura_ace_internal_SimpleMessage_descriptor,
        new java.lang.String[] { "IntValue", "LongValue", "StringValue", "FloatValue", "DoubleValue", "BoolValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
